"use client";

import { useState } from "react";
import { PatientProfile } from "@/components/dashboard/PatientProfile";
import { HealthCharts } from "@/components/dashboard/HealthCharts";
import { DietTracker } from "@/components/dashboard/DietTracker";
import { YogaTracker } from "@/components/dashboard/YogaTracker";
import { CaretakerCard } from "@/components/dashboard/CaretakerCard";
import { EditProfileDialog } from "@/components/dashboard/EditProfileDialog";
import { WhatsAppButton } from "@/components/dashboard/WhatsAppButton";
import { Button } from "@/components/ui/button";
import { Upload, Calendar as CalendarIcon, FileText } from "lucide-react";

// Initial Mock Data
const initialPatientData = {
    name: "Ram Prasad",
    age: "72",
    bloodGroup: "O+",
    condition: "Dementia (Stage 2)",
    address: "123, Gandhi Nagar, Bhubaneswar, Odisha",
    phone: "+91 98765 43210",
    history: [
        { event: "Diagnosed with Mild Dementia", date: "Jan 2024", color: "bg-green-500" },
        { event: "Hypertension Detected", date: "Nov 2023", color: "bg-gray-300" },
    ]
};

// Doctor/Caregiver Data - Real Doctors from Odisha
const doctorData = {
    name: "Dr. Jyoti Narayan Das",
    specialty: "Pattamundai, Odisha",
    phone: "+91 70779 91009",
    whatsappNumber: "917077991009",
    avatar: "/images/caretaker.png"
};

export default function CaregiverDashboard() {
    const [patientData, setPatientData] = useState(initialPatientData);

    const generateProgressReport = () => {
        const currentDate = new Date().toLocaleString('en-IN', {
            dateStyle: 'medium',
            timeStyle: 'short',
            timeZone: 'Asia/Kolkata'
        });

        return `📊 *PATIENT PROGRESS REPORT*
Generated: ${currentDate}

👤 *Patient Details*
Name: ${patientData.name}
Age: ${patientData.age} years
Condition: ${patientData.condition}
Blood Group: ${patientData.bloodGroup}
Phone: ${patientData.phone}

💓 *Current Vitals*
Heart Rate: 78 bpm ❤️
Blood Pressure: 120/80 mmHg 🩺

🧠 *Cognitive Performance*
Weekly Average: 68/100
Latest Score: 74/100
Trend: ↗️ Improving

😊 *Mood Analysis*
Weekly Average: 4.0/5
Status: Good 👍

🍽️ *Diet Tracking (Today)*
✅ Breakfast - Completed
✅ Lunch - Completed
⏳ Snacks - Pending
⏳ Dinner - Pending

🧘 *Exercise Progress*
Daily Goal: 75% Complete
Streak: 12 days 🔥
Total Time: 45 minutes

📋 *Medical History*
${patientData.history.map(item => `• ${item.event} - ${item.date}`).join('\n')}

---
Report generated by MedhAsha Care Platform 🏥
For any concerns, please contact the healthcare provider.`;
    };

    return (
        <div className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-blue-50 p-4 md:p-8 space-y-8">
            {/* Header Section */}
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                <div>
                    <h1 className="text-3xl font-bold text-gray-900">Caregiver Dashboard</h1>
                    <p className="text-muted-foreground">Welcome back, Priya. Here's today's update for {patientData.name.split(' ')[0]}.</p>
                </div>
                <div className="flex gap-3">
                    <Button variant="outline" className="gap-2 bg-white/50 backdrop-blur-sm">
                        <CalendarIcon className="h-4 w-4" /> Schedule
                    </Button>
                    <Button className="gap-2 shadow-lg shadow-primary/20">
                        <Upload className="h-4 w-4" /> Upload Report
                    </Button>
                    <WhatsAppButton onGenerateReport={generateProgressReport} />
                </div>
            </div>

            {/* Main Grid Layout */}
            <div className="grid grid-cols-1 md:grid-cols-12 gap-6">
                {/* Left Column: Profile & Trackers (4 cols) */}
                <div className="md:col-span-4 space-y-6">
                    <div className="relative group">
                        <PatientProfile data={patientData} />
                        <div className="absolute top-4 right-4 opacity-0 group-hover:opacity-100 transition-opacity">
                            <EditProfileDialog data={patientData} onSave={setPatientData} />
                        </div>
                    </div>

                    {/* Doctor Cards - All Available Doctors */}
                    <div className="space-y-4">
                        <CaretakerCard doctor={{
                            name: "Dr. Jyoti Narayan Das",
                            specialty: "Pattamundai, Odisha",
                            phone: "+91 70779 91009",
                            whatsappNumber: "917077991009",
                            avatar: "/images/doctors/dr-jyoti.png"
                        }} />
                        <CaretakerCard doctor={{
                            name: "Dr. Bhagyabati Das",
                            specialty: "Aul, Odisha",
                            phone: "+91 94382 73089",
                            whatsappNumber: "919438273089",
                            avatar: "/images/doctors/dr-bhagyabati.png"
                        }} />
                        <CaretakerCard doctor={{
                            name: "Dr. Madhusmita",
                            specialty: "Odisha",
                            phone: "+91 93484 22438",
                            whatsappNumber: "919348422438",
                            avatar: "/images/doctors/dr-madhusmita.png"
                        }} />
                    </div>
                </div>

                {/* Right Column: Charts & Detailed Trackers (8 cols) */}
                <div className="md:col-span-8 space-y-6">
                    {/* Health Charts Row */}
                    <HealthCharts />

                    {/* Trackers Row */}
                    <div className="grid md:grid-cols-2 gap-6">
                        <DietTracker />
                        <YogaTracker />
                    </div>

                    {/* Recent Reports Stub (Glassmorphism) */}
                    <div className="bg-white/50 backdrop-blur-md rounded-xl p-6 shadow-lg border border-white/20">
                        <div className="flex justify-between items-center mb-4">
                            <h3 className="font-semibold text-lg flex items-center gap-2">
                                <FileText className="h-5 w-5 text-blue-500" /> Recent Reports
                            </h3>
                            <Button variant="ghost" size="sm">View All</Button>
                        </div>
                        <div className="space-y-3">
                            {[1, 2].map((i) => (
                                <div key={i} className="flex items-center justify-between p-3 bg-white/60 rounded-lg hover:bg-white/80 transition-colors cursor-pointer">
                                    <div className="flex items-center gap-3">
                                        <div className="h-10 w-10 bg-blue-100 rounded-lg flex items-center justify-center text-blue-600">
                                            <FileText className="h-5 w-5" />
                                        </div>
                                        <div>
                                            <p className="font-medium text-sm">Blood_Test_Report.pdf</p>
                                            <p className="text-xs text-muted-foreground">Uploaded 2 days ago</p>
                                        </div>
                                    </div>
                                    <span className="text-xs font-medium bg-green-100 text-green-700 px-2 py-1 rounded-full">Verified</span>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
